export const ON_CHANGE_NAME = 'ON_CHANGE_NAME';
export const ON_CHANGE_LOCKED = 'ON_CHANGE_LOCKED';
export const ON_CHANGE_DATE = 'ON_CHANGE_DATE';
export const ON_CHANGE_DURATION = 'ON_CHANGE_DURATION';
export const ON_CHANGE_SHIPPING = 'ON_CHANGE_SHIPPING';
export const ON_CHANGE_ACCOUNT = 'ON_CHANGE_ACCOUNT';
export const SET_STEP = 'SET_STEP';